exports.SUBSCRIPTION = [
  { name: 'app_name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'app_apple_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_apple_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_group_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_duration', type: 'STRING', mode: 'NULLABLE', },
  { name: 'customer_price', type: 'STRING', mode: 'NULLABLE', },
  { name: 'customer_currency', type: 'STRING', mode: 'NULLABLE', },
  { name: 'proceeds', type: 'STRING', mode: 'NULLABLE', },
  { name: 'proceeds_currency', type: 'STRING', mode: 'NULLABLE', },
  { name: 'preserved_pricing', type: 'STRING', mode: 'NULLABLE', },
  { name: 'proceeds_reason', type: 'STRING', mode: 'NULLABLE', },
  { name: 'client', type: 'STRING', mode: 'NULLABLE', },
  { name: 'device', type: 'STRING', mode: 'NULLABLE', },
  { name: 'state', type: 'STRING', mode: 'NULLABLE', },
  { name: 'country', type: 'STRING', mode: 'NULLABLE', },
  { name: 'active_subscriptions', type: 'STRING', mode: 'NULLABLE', },
  { name: 'active_free_trials', type: 'STRING', mode: 'NULLABLE', },
  { name: 'active_pay_up_front_subscriptions', type: 'STRING', mode: 'NULLABLE', },
  { name: 'active_pay_as_you_go_subscriptions', type: 'STRING', mode: 'NULLABLE', },
  { name: 'marketing_opt_ins', type: 'STRING', mode: 'NULLABLE', },
  { name: 'billing_retry', type: 'STRING', mode: 'NULLABLE', }
];

exports.SUBSCRIPTION_EVENT = [
  { name: 'event_date', type: 'STRING', mode: 'NULLABLE', },
  { name: 'event', type: 'STRING', mode: 'NULLABLE', },
  { name: 'app_name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'app_apple_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_apple_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_group_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'subscription_duration', type: 'STRING', mode: 'NULLABLE', },
  { name: 'trial', type: 'STRING', mode: 'NULLABLE', },
  { name: 'introductory_price_type', type: 'STRING', mode: 'NULLABLE', },
  { name: 'trial_duration', type: 'STRING', mode: 'NULLABLE', },
  { name: 'introductory_price_duration', type: 'STRING', mode: 'NULLABLE', },
  { name: 'marketing_opt_in', type: 'STRING', mode: 'NULLABLE', },
  { name: 'preserved_pricing', type: 'STRING', mode: 'NULLABLE', },
  { name: 'proceeds_reason', type: 'STRING', mode: 'NULLABLE', },
  { name: 'consecutive_paid_periods', type: 'STRING', mode: 'NULLABLE', },
  { name: 'original_start_date', type: 'STRING', mode: 'NULLABLE', },
  { name: 'device', type: 'STRING', mode: 'NULLABLE', },
  { name: 'client', type: 'STRING', mode: 'NULLABLE', },
  { name: 'country', type: 'STRING', mode: 'NULLABLE', },
  { name: 'previous_subscription_name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'previous_subscription_apple_id', type: 'STRING', mode: 'NULLABLE', },
  { name: 'days_before_canceling', type: 'STRING', mode: 'NULLABLE', },
  { name: 'cancellation_reason', type: 'STRING', mode: 'NULLABLE', },
  { name: 'days_canceled', type: 'STRING', mode: 'NULLABLE', },
  { name: 'quantity', type: 'STRING', mode: 'NULLABLE', }
];

exports.SALES = [
  { name: 'date', type: 'STRING', mode: 'NULLABLE', },
  { name: 'name', type: 'STRING', mode: 'NULLABLE', },
  { name: 'event', type: 'STRING', mode: 'NULLABLE', },
  { name: 'metric', type: 'STRING', mode: 'NULLABLE', },
  { name: 'territory', type: 'STRING', mode: 'NULLABLE', },
  { name: 'device', type: 'STRING', mode: 'NULLABLE', },
  { name: 'time_frame', type: 'STRING', mode: 'NULLABLE', },
  { name: 'apple_identifier', type: 'STRING', mode: 'NULLABLE', },
];